export enum ImageAsset {
  ArrowKeys = "arrow-keys",
  Bamboo = "bamboo",
  BlackHole = "black-hole",
  Boat = "boat",
  Bomb = "bomb",
  Bones = "bones",
  BoobyTrap = "booby-trap",
  Cactus = "cactus",
  Cloud = "cloud",
  CrackedRainbowGlitter = "cracked-rainbow-glitter",
  CuteSpider = "cute-spider",
  Elasmosaurus = "elasmosaurus",
  EvilGuy = "evil-guy",
  Forest = "forest",
  Friend = "friend",
  Goo = "goo",
  Grass = "grass",
  GumDrop = "gum-drop",
  Heart = "heart",
  LandingPad = "landing-pad",
  LittleSister = "little-sister",
  Lollipop = "lollipop",
  Lungs = "lungs",
  MagicalCraft = "magical-craft",
  MagicLollipopKey = "magic-lollipop-key",
  MagicTree = "magic-tree",
  Mine = "mine",
  Monster = "monster",
  MonsterGuts = "monster-guts",
  MountainSpikes = "mountain-spikes",
  MrDung = "mr-dung",
  MrRainbow = "mr-rainbow",
  NiceOldLady = "nice-old-lady",
  OompaBall = "oompa-ball",
  Peppermint = "peppermint",
  Platform = "platform",
  PooGuy = "poo-guy",
  Portal = "portal",
  PurpleAcid = "purple-acid",
  Queen = "queen",
  RainbowGlitter = "rainbow-glitter",
  Sand = "sand",
  SandDown = "sand-down",
  SandLeft = "sand-left",
  SandRight = "sand-right",
  SandUp = "sand-up",
  Sky = "sky",
  SmallElasmosaurus = "small-elasmosaurus",
  Snaggletooth = "snaggletooth",
  SpikeBench = "spike-bench",
  SpikyGuy = "spiky-guy",
  SquareSpike = "square-spike",
  Star = "star",
  Stone = "stone",
  ThreeSpikes = "three-spikes",
  ToddieTitan = "toddie-titan",
  Tree = "tree",
  Warewolf = "warewolf",
  Water = "water",
}

export const defaultImages = [
  ImageAsset.Bamboo,
  ImageAsset.CuteSpider,
  ImageAsset.Friend,
  ImageAsset.MrDung,
  ImageAsset.MrRainbow,
  ImageAsset.OompaBall,
  ImageAsset.PooGuy,
  ImageAsset.Snaggletooth,
  ImageAsset.ToddieTitan,
  ImageAsset.Warewolf,
] as const;
export type DefaultImageAsset = (typeof defaultImages)[number];
