export enum ImageAsset {
  Boat = "boat",
  Mine = "mine",
  Cloud = "cloud",
  Grass = "grass",
  Heart = "heart",
  Bomb = "bomb",
  Platform = "platform",
  Sand = "sand",
  Sky = "sky",
  Star = "star",
  Water = "water",
  Stone = "stone",
  BlackHole = "black-hole",
  Monster = "monster",
  Portal = "portal",
  Goo = "goo",
  Lungs = "lungs",
  Elasmosaurus = "elasmosaurus",
  SmallElasmosaurus = "small-elasmosaurus",
  Bones = "bones",
  Forest = "forest",
  Friend = "friend",
  Tree = "tree",
  MagicTree = "magic-tree",
  Cactus = "cactus",
  BoobyTrap = "booby-trap",
  ThreeSpikes = "three-spikes",
  MountainSpikes = "mountain-spikes",
  SpikeBench = "spike-bench",
  SquareSpike = "square-spike",
  LandingPad = "landing-pad",
  SpikyGuy = "spiky-guy",
  Queen = "queen",
}

export const defaultImages = [ImageAsset.Friend] as const;
export type DefaultImageAsset = (typeof defaultImages)[number];
