export enum ImageAsset {
  Boat = "boat",
  Mine = "mine",
  Cloud = "cloud",
  Grass = "grass",
  Heart = "heart",
  Bomb = "bomb",
  Platform = "platform",
  Sand = "sand",
  Sky = "sky",
  Star = "star",
  Water = "water",
  Stone = "stone",
  BlackHole = "black-hole",
  Monster = "monster",
  Portal = "portal",
  Goo = "goo",
  Lungs = "lungs",
  Elasmosaurus = "elasmosaurus",
  SmallElasmosaurus = "small-elasmosaurus",
  Bones = "bones",
  Forest = "forest",
  Friend = "friend",
}

export const ImageAssets: Record<ImageAsset, string> = {
  [ImageAsset.Boat]: "assets/image/boat.png",
  [ImageAsset.Mine]: "assets/image/mine.png",
  [ImageAsset.Cloud]: "assets/image/cloud.png",
  [ImageAsset.Grass]: "assets/image/grass.png",
  [ImageAsset.Heart]: "assets/image/heart.png",
  [ImageAsset.Bomb]: "assets/image/bomb.png",
  [ImageAsset.Platform]: "assets/image/platform.png",
  [ImageAsset.Sand]: "assets/image/sand.png",
  [ImageAsset.Sky]: "assets/image/sky.png",
  [ImageAsset.Star]: "assets/image/star.png",
  [ImageAsset.Water]: "assets/image/water.png",
  [ImageAsset.Stone]: "assets/image/stone.png",
  [ImageAsset.BlackHole]: "assets/image/black-hole.png",
  [ImageAsset.Monster]: "assets/image/monster.png",
  [ImageAsset.Portal]: "assets/image/portal.png",
  [ImageAsset.Goo]: "assets/image/goo.png",
  [ImageAsset.Lungs]: "assets/image/lungs.png",
  [ImageAsset.SmallElasmosaurus]: "assets/image/small-elasmosaurus.png",
  [ImageAsset.Elasmosaurus]: "assets/image/elasmosaurus.png",
  [ImageAsset.Bones]: "assets/image/bones.png",
  [ImageAsset.Forest]: "assets/image/forest.png",
  [ImageAsset.Friend]: "assets/image/friend.png",
};
